#!/usr/bin/perl
#------------------------------------------------------------------------------
# SQL queries generated by pgcluu_collectd for each PostgreSQL version.
#
# The dump_* functions of pgcluu_collectd are evaluated alone with a forced
# server version, no PostgreSQL server is needed. All queries are compared
# with a snapshot (t/expected/collectd_sql.json) so that any change of the
# collected columns for a version is visible, and some version specific rules
# are tested explicitly.
#------------------------------------------------------------------------------
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use Test::More;
use PgcluuTest;

my $script = root_dir() . '/pgcluu_collectd';

# Functions called by the metrics, read from %METRICS_COMMANDS
my $src = do { local $/; open(my $fh, '<', $script) or die; <$fh> };
my %seen = ();
my @dumps = grep { !$seen{$_}++ } ($src =~ /'command'\s*=>\s*'(dump_\w+)'/g);
ok(scalar @dumps > 40, 'metric functions found in pgcluu_collectd');

# Functions called by other functions are loaded too
my @deps = ('backend_minimum_version', 'dump_pgstattables', 'dump_pgstatindexes',
	'dump_pgstatiotables', 'dump_pgstatioindexes', 'dump_pgstatiosequences',
	'dump_pgstatxacttables');
%seen = ();
load_subs($script, 'Collectd', grep { !$seen{$_}++ } (@deps, @dumps));

no warnings 'once';
$Collectd::DB_INFO{pg_stat_statement} = 'public.pg_stat_statements';
$Collectd::LOCK_TIMEOUT = 3;
$Collectd::CAPTURE = 0;
$Collectd::STAT_TYPE = 'user';

my @versions = ('9.6', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19');
my %snapshot = ();
foreach my $v (@versions)
{
	my ($major, $minor) = split(/\./, $v);
	$Collectd::DB_INFO{major} = $major;
	$Collectd::DB_INFO{minor} = $minor || 0;
	foreach my $f (@dumps)
	{
		my $sql = eval { no strict 'refs'; &{"Collectd::$f"}() };
		if ($@ || !defined $sql || $sql eq '') {
			fail("$f returns a query for PostgreSQL $v") ;
			diag($@) if ($@);
			next;
		}
		$snapshot{$v}{$f} = $sql;
	}
}

# Version specific rules
like($snapshot{16}{dump_pgstatio}, qr/reads\*op_bytes AS read_bytes/, 'PG16: pg_stat_io bytes computed from op_bytes');
like($snapshot{17}{dump_pgstatio}, qr/writes\*op_bytes AS write_bytes/, 'PG17: pg_stat_io bytes computed from op_bytes');
foreach my $v ('18', '19') {
	unlike($snapshot{$v}{dump_pgstatio}, qr/op_bytes/, "PG$v: op_bytes is not used (removed in PG18)");
	like($snapshot{$v}{dump_pgstatio}, qr/read_bytes, read_time/, "PG$v: native read_bytes column");
	unlike($snapshot{$v}{dump_pgstatbgwriter}, qr/op_bytes/, "PG$v: bgwriter query does not use op_bytes");
}
like($snapshot{18}{dump_pgstataio}, qr/NULL, NULL/, 'PG18: no io_min_workers/io_max_workers');
like($snapshot{19}{dump_pgstataio}, qr/current_setting\('io_max_workers', true\)/, 'PG19: io_max_workers collected');
like($snapshot{17}{dump_pgstatbgwriter}, qr/pg_stat_checkpointer/, 'PG17: checkpointer statistics from pg_stat_checkpointer');
unlike($snapshot{16}{dump_pgstatbgwriter}, qr/pg_stat_checkpointer/, 'PG16: no pg_stat_checkpointer');

# Every column of the normalized pg_stat_io output is present in the same order
my @iocols = qw(backend_type object context reads read_bytes read_time writes
	write_bytes write_time writebacks writeback_time extends extend_bytes
	extend_time hits evictions reuses fsyncs fsync_time block_size);
foreach my $v ('16', '17', '18', '19')
{
	my $sql = $snapshot{$v}{dump_pgstatio};
	my $pos = 0;
	my $ordered = 1;
	foreach my $c (@iocols) {
		my $p = index($sql, $c, $pos);
		if ($p < 0) { $ordered = 0; last; }
		$pos = $p;
	}
	ok($ordered, "PG$v: pg_stat_io output columns in the expected order");
}

check_expected(\%snapshot, 'collectd_sql.json', 'collectd SQL');

done_testing();
