#!/usr/bin/perl
#------------------------------------------------------------------------------
# HTML reports generated by pgcluu from the fixtures.
#
# For each fixture (statistics collected on a PostgreSQL major version) the
# report is generated and every page is compared with the expected results
# in t/expected/report-<fixture>.json: list of pages, graph titles, series
# labels, data points and table rows.
#------------------------------------------------------------------------------
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use Test::More;
use PgcluuTest;

my $root = root_dir();

foreach my $fixture (fixtures())
{
	my $out = tmp_dir();
	my ($rc, $stdout, $stderr) = run_cmd($^X, "$root/pgcluu", '-S', '-o', $out, fixture_dir($fixture));
	is($rc, 0, "$fixture: pgcluu exits with 0") or diag($stderr);

	# Only the notice about the missing pidstat file is expected
	my @errors = grep { !/No pidstat data file found|Continuing normally/ && /\S/ } split(/\n/, $stderr . $stdout);
	is_deeply(\@errors, [], "$fixture: no error or warning") or diag(join("\n", @errors));

	my $report = normalize_report_dir($out);
	ok(exists $report->{'index.html'}, "$fixture: index.html is generated");

	# A second generation must give exactly the same result, this detects
	# data built in hash order.
	my $out2 = tmp_dir();
	run_cmd($^X, "$root/pgcluu", '-S', '-o', $out2, fixture_dir($fixture));
	is_deeply(normalize_report_dir($out2), $report, "$fixture: report generation is deterministic");

	check_expected($report, "report-$fixture.json", "$fixture report");
}

done_testing();
