#!/usr/bin/perl
#------------------------------------------------------------------------------
# The javascript embedded in each page of the reports must be valid: the
# graph data are generated by pgcluu and a malformed value (empty value, NaN,
# missing comma) breaks the whole page. Requires node to check the syntax.
#------------------------------------------------------------------------------
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use Test::More;
use PgcluuTest;

plan skip_all => 'node is not installed' if (!have_node());

my $root = root_dir();
foreach my $fixture (fixtures())
{
	my $out = tmp_dir();
	my ($rc) = run_cmd($^X, "$root/pgcluu", '-S', '-o', $out, fixture_dir($fixture));
	is($rc, 0, "$fixture: report generated");

	foreach my $page (html_pages($out))
	{
		my $html = do { local $/; open(my $fh, '<', "$out/$page") or die; <$fh> };
		my @scripts = ($html =~ m{/\* <!\[CDATA\[ \*/(.*?)/\* \]\]> \*/}gs);
		next if ($#scripts < 0);
		my $js = join("\n", @scripts);
		unlike($js, qr/\bNaN\b|\binf\b|\[,|,,/i, "$fixture/$page: no invalid value in graph data");
		my $file = "$out/$page.js";
		open(my $fh, '>', $file) or die;
		print $fh $js;
		close($fh);
		my ($rc2, $o, $err) = run_cmd('node', '--check', $file);
		is($rc2, 0, "$fixture/$page: javascript syntax") or diag($err);
	}
}

done_testing();
